### ISSUE TITLE
No maches found error for slice, pointer, slice of pointer

### ISSUE THREAD

**Issue by wawoon** [vektah/dataloaden#29]
I upgraded the dataloaden version to latest v0.3.0, it starts to show following error.

```
$ dataloaden UserSliceLoader int []*github.com/vektah/dataloaden/example.User

zsh: no matches found: []*github.com/vektah/dataloaden/example.User
```

I don't know this is my environment problem, but I succeeded to generate dataloader for normal struct and other self defined types.

```
$ dataloaden UserLoader int github.com/vektah/dataloaden/example.User
```

Now I avoid this error by defining new type of slice, and slice of pointers, like below.
```
type UserSlice []User
type UserPointerSlice []*User
type UserPointer *User
```

My environment is MacOS, zsh, go 1.12.5.

**Comment by k-komarov** [comment]
+1

**Comment by wawoon** [comment]
I'm sorry for being late to reply. It works!
Thank you.
