### ISSUE TITLE
Any recipes to use dataloaden with Gin?

### ISSUE THREAD

**Issue by mirusky** [vektah/dataloaden#56]
I'm looking for a pattern or a recipe to use dataloaden with gin is there some approach?

**Comment by bRRRITSCOLD** [comment]
I cavear the below with I just started exploring golang over the past few weeks (senior backend node dev currently), **BUT!!!!!!**

I have been working on a solution over the weekend, [repo](https://github.com/bRRRITSCOLD/golang-mongo-graphql-003) (inspired partially by [partial example](https://medium.com/swlh/lets-build-a-graphql-server-in-go-af6d35448b0c) - minus gin and mongodb) - no real README yet on how to start this up or use it, I will work on that over the coming weeks as I have time.

[Server Start Up](https://github.com/bRRRITSCOLD/golang-mongo-graphql-003/blob/main/server.go)
[Internal API Dataloaders Package](https://github.com/bRRRITSCOLD/golang-mongo-graphql-003/tree/main/internal/dataloaders)
[First Example Usage In Resolver](https://github.com/bRRRITSCOLD/golang-mongo-graphql-003/blob/main/internal/api/author.resolvers.go) - begins line 17

**Comment by mirusky** [comment]
Hi @bRRRITSCOLD a person helped me to setup a minimal example in (https://github.com/99designs/gqlgen/issues/1439). You could find a very usefull resources there if u need this kind of implementation.

I will close this issue since we have an answer
