### ISSUE TITLE
can't generate loader, no matches found

### ISSUE THREAD

**Issue by Abdubek** [vektah/dataloaden#58]
go run github.com/vektah/dataloaden ProjectLoader int *myprivate.domain/backend.api/internal/domain.Project

zsh: no matches found: *myprivate.domain/backend.api/internal/domain.Project

how can this be solved?

![image](https://user-images.githubusercontent.com/16240224/116392407-3d055680-a842-11eb-9547-6e5d5c313fc7.png)

**Comment by Abdubek** [comment]
I found a solution here, https://github.com/vektah/dataloaden/issues/35, and wrote without an asterisk

**Comment by koslib** [comment]
Am I the only one who still has this problem? I can generate the dataloader file by specifying `github.com/my/package.Model`, however it **always** fails when I do `[]*github.com/my/package.Model`. Any ideas on this?

**Comment by yunkaiOr2** [comment]
```shell
go run github.com/vektah/dataloaden ProjectLoader int "*myprivate.domain/backend.api/internal/domain.Project"
```
can fix it
